### PR TITLE
license: change to BSL 1.1

### PR DESCRIPTION
**Pull request by armurbalda**
As a contributor, please reply with `ACK` as comment below to confirm your consent for the license change. @michael1011, @dni, @tiero, @peartobear, @ImmanuelSegol, @yuyaogawa

### CODE REVIEW

**Comment by ImmanuelSegol** [comment]
Acknowledging

**Comment by peartobear** [comment]
ACK

**Comment by michael1011** [comment]
ACK

**Review by michael1011 — APPROVED** [review]

**Review by dni — APPROVED** [review]
ACK

**Comment by yuyaogawa** [comment]
ACK

**Comment by tiero** [comment]
ACK

**Comment by armurbalda** [comment]
Thanks y'all

image

**Pull request merged**
