### PR TITLE
chore: change license to AGPL-3

### PR DESCRIPTION
**Pull request by kilrau**
This PR reverts https://github.com/BoltzExchange/boltz-backend/pull/323 returning to AGPLv3. Credit to @kingonly who convinced us of doing this.

As a contributor, please reply with "ACK" as comment below to confirm your consent for the license change! @michael1011 @dni @tiero @peartobear @ImmanuelSegol @yuyaogawa

This PR represents my ACK.

### CODE REVIEW

**Comment by tiero** [comment]
ACK

**Comment by peartobear** [comment]
ACK

**Review by michael1011 — CHANGES_REQUESTED** [review]
ACK but README wasn't changed

**Comment by dni** [comment]
ACK

**Comment by kilrau** [comment]
> ACK but README wasn't changed

:man_facepalming: fixed

Could you check on https://github.com/BoltzExchange/boltz-backend/actions/runs/9611545445/job/26510327034?pr=574#step:11:32 ? @michael1011

**Review by michael1011 — APPROVED** [review]

**Comment by ImmanuelSegol** [comment]
ACK

**Pull request merged**
